name: Deploy Code to Release Branch
on:
  workflow_dispatch:
jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
